import type { SessionStats, TorrentState, TorrentStatus } from "./types";

function torrent(
  id: string,
  partial: Pick<TorrentStatus, "name" | "state" | "progress"> &
    Partial<TorrentStatus>
): [string, TorrentStatus] {
  const total = partial.total_wanted ?? 4_294_967_296;
  const progress = partial.progress;
  const done = Math.round((total * progress) / 100);
  return [
    id,
    {
      queue: 0,
      total_wanted: total,
      num_seeds: 0,
      total_seeds: 0,
      num_peers: 0,
      total_peers: 0,
      download_payload_rate: 0,
      upload_payload_rate: 0,
      eta: -1,
      ratio: 0,
      distributed_copies: 0,
      is_auto_managed: true,
      time_added: 1_724_000_000,
      tracker_host: "opentrackr.org",
      download_location: "/data/downloads",
      last_seen_complete: 1_724_800_000,
      total_done: done,
      total_uploaded: Math.round(done * (partial.ratio ?? 0)),
      max_download_speed: -1,
      max_upload_speed: -1,
      seeds_peers_ratio: 1,
      total_remaining: total - done,
      completed_time: progress >= 100 ? 1_724_700_000 : 0,
      time_since_transfer: 12,
      total_payload_download: done,
      total_payload_upload: Math.round(done * (partial.ratio ?? 0)),
      next_announce: 1800,
      tracker_status: "Announce OK",
      num_pieces: 2048,
      piece_length: 2_097_152,
      active_time: 86_400,
      seeding_time: progress >= 100 ? 40_000 : 0,
      seed_rank: 0,
      owner: "localclient",
      public: true,
      shared: false,
      total_size: total,
      num_files: 1,
      message: "",
      comment: "",
      creator: "Deluge",
      max_connections: -1,
      max_upload_slots: -1,
      stop_at_ratio: false,
      stop_ratio: 2,
      remove_at_ratio: false,
      private: false,
      prioritize_first_last: false,
      move_completed: false,
      move_completed_path: "/data/complete",
      super_seeding: false,
      sequential_download: false,
      ...partial,
    },
  ];
}

export const DEMO_TORRENTS: Record<string, TorrentStatus> = Object.fromEntries([
  torrent("a1", {
    queue: 1,
    name: "debian-13.0.0-amd64-netinst.iso",
    state: "Downloading",
    progress: 67.4,
    total_wanted: 701_628_416,
    num_seeds: 48,
    total_seeds: 312,
    num_peers: 22,
    total_peers: 89,
    download_payload_rate: 8_388_608,
    upload_payload_rate: 524_288,
    eta: 54,
    ratio: 0.214,
    tracker_host: "bttracker.debian.org",
    label: "linux",
    num_files: 1,
  }),
  torrent("a2", {
    queue: 2,
    name: "ubuntu-24.04.2-desktop-amd64.iso",
    state: "Downloading",
    progress: 23.1,
    total_wanted: 5_872_689_152,
    num_seeds: 120,
    total_seeds: 1840,
    num_peers: 64,
    total_peers: 410,
    download_payload_rate: 14_680_064,
    upload_payload_rate: 1_048_576,
    eta: 318,
    ratio: 0.041,
    tracker_host: "torrent.ubuntu.com",
    label: "linux",
    num_files: 1,
  }),
  torrent("a3", {
    queue: 3,
    name: "archlinux-2026.08.01-x86_64.iso",
    state: "Seeding",
    progress: 100,
    total_wanted: 1_258_291_200,
    num_seeds: 0,
    total_seeds: 210,
    num_peers: 11,
    total_peers: 11,
    download_payload_rate: 0,
    upload_payload_rate: 3_145_728,
    eta: -1,
    ratio: 4.812,
    tracker_host: "tracker.archlinux.org",
    label: "linux",
  }),
  torrent("a4", {
    queue: 4,
    name: "Fedora-Workstation-Live-42-1.1.x86_64.iso",
    state: "Seeding",
    progress: 100,
    total_wanted: 2_415_919_104,
    num_seeds: 0,
    total_seeds: 96,
    num_peers: 4,
    total_peers: 4,
    upload_payload_rate: 786_432,
    ratio: 1.640,
    tracker_host: "torrent.fedoraproject.org",
    label: "linux",
  }),
  torrent("a5", {
    queue: 5,
    name: "blender-4.5.0-linux-x64.tar.xz",
    state: "Paused",
    progress: 41.8,
    total_wanted: 326_107_136,
    num_seeds: 0,
    total_seeds: 18,
    num_peers: 0,
    total_peers: 7,
    eta: -1,
    ratio: 0.0,
    tracker_host: "download.blender.org",
    label: "apps",
  }),
  torrent("a6", {
    queue: 6,
    name: "openstreetmap-europe-latest.osm.pbf",
    state: "Downloading",
    progress: 8.6,
    total_wanted: 28_749_946_880,
    num_seeds: 6,
    total_seeds: 14,
    num_peers: 19,
    total_peers: 33,
    download_payload_rate: 4_194_304,
    upload_payload_rate: 65_536,
    eta: 6_240,
    ratio: 0.008,
    tracker_host: "planet.openstreetmap.org",
    label: "data",
    num_files: 1,
  }),
  torrent("a7", {
    queue: 7,
    name: "wikimedia-commons-2026-08",
    state: "Checking",
    progress: 91.2,
    total_wanted: 12_884_901_888,
    num_seeds: 2,
    total_seeds: 9,
    num_peers: 1,
    total_peers: 5,
    eta: 420,
    ratio: 0.552,
    tracker_host: "dumps.wikimedia.org",
    label: "data",
    num_files: 48,
    message: "Checking pieces",
  }),
  torrent("a8", {
    queue: 8,
    name: "linux-firmware-20260812.tar.xz",
    state: "Queued",
    progress: 0,
    total_wanted: 754_974_720,
    total_seeds: 44,
    total_peers: 12,
    eta: -1,
    ratio: 0,
    tracker_host: "cdn.kernel.org",
    label: "linux",
  }),
  torrent("a9", {
    queue: 9,
    name: "LibreOffice_25.8_Linux_x86-64_deb.tar.gz",
    state: "Error",
    progress: 12.0,
    total_wanted: 267_386_880,
    eta: -1,
    ratio: 0.002,
    tracker_host: "download.documentfoundation.org",
    label: "apps",
    message: "Tracker returned no peers",
  }),
  torrent("a10", {
    queue: 10,
    name: "gimp-3.0.4-x86_64.AppImage",
    state: "Seeding",
    progress: 100,
    total_wanted: 198_180_864,
    num_peers: 3,
    total_peers: 3,
    upload_payload_rate: 212_992,
    ratio: 2.104,
    tracker_host: "download.gimp.org",
    label: "apps",
  }),
]);

export const DEMO_STATS: SessionStats = {
  max_download: -1,
  max_upload: 5_242_880,
  max_num_connections: 200,
  num_connections: 186,
  upload_rate: 5_783_552,
  download_rate: 27_262_976,
  download_protocol_rate: 180_224,
  upload_protocol_rate: 40_960,
  dht_nodes: 284,
  has_incoming_connections: true,
  free_space: 1_318_479_495_168,
  external_ip: "203.0.113.42",
};

export const DEMO_FILES: Record<string, string[]> = {
  a1: ["debian-13.0.0-amd64-netinst.iso"],
  a2: ["ubuntu-24.04.2-desktop-amd64.iso"],
  a3: ["archlinux-2026.08.01-x86_64.iso"],
  a4: ["Fedora-Workstation-Live-42-1.1.x86_64.iso"],
  a5: ["blender-4.5.0-linux-x64.tar.xz"],
  a6: ["openstreetmap-europe-latest.osm.pbf"],
  a7: [
    "commonswiki-20260801-pages-articles.xml.bz2",
    "commonswiki-20260801-imageinfo.sql.gz",
    "commonswiki-20260801-imagelinks.sql.gz",
  ],
  a8: ["linux-firmware-20260812.tar.xz"],
  a9: ["LibreOffice_25.8_Linux_x86-64_deb.tar.gz"],
  a10: ["gimp-3.0.4-x86_64.AppImage"],
};

export function matchesFilter(state: TorrentState, filter: string): boolean {
  if (filter === "All") return true;
  if (filter === "Active") {
    return state === "Downloading" || state === "Seeding" || state === "Checking";
  }
  return state === filter;
}
